### ISSUE TITLE
Xiaomi non-Aqara (WSDCGQ01LM) "round" temperature/humidity sensor not working

### ISSUE THREAD

**Issue by rickardp** [TedTolboom/com.xiaomi-mi-zigbee#10]
There appears to be code for it in the repo, but the driver is never used.

I assume there are some problems with it? I don't know if it is within the scope of this project to support these sensors.

**Comment by rickardp** [comment]
After reading the code some more I understand that the code for parsing the value out of the sensor is not even there, it appears the device is sending the data in a non-standard format.

I managed to extract the temperature and humidity information by parsing the string returned from the 65281 attribute (basically by putting the sensor in various places (like my freezer) and comparing values with the Aqara sensor. I did not find documentation on the format of this string, so I am not sure what the other bytes do, but I assume the battery status etc is also in there.

**Comment by TedTolboom** [comment]
Hi @rickardp,

The reason why the round temperature / humidity sensor has not been included in the app store release is that the temperature and humidity clusters are not registered (correctly) during inclusion... When I check the wireshark logs, the device does send the attribute reports for both clusters.

Since these clusters are not available, the check on availability of the devices endpoint/cluster during registering the registerAttrReportListener in the meshdriver fails. 
If this check (in the meshdriver) is overrulled/disabled (https://github.com/TedTolboom/com.xiaomi-mi-zigbee/blob/master/node_modules/homey-meshdriver/lib/zigbee/ZigBeeDevice.js#L552), the attribute reports send are accurately parsed and data will show up on the mobile card instantly.

I'm currently checking with the Athom team to get the required modifications implemented into the meshdriver. If it is possible get this implemented, this would be my preference (closest to standard implementation).

I do like the approach you took with the 65281 attribute. Nice thinking!
Does the temperature and humidity update automatically with your sensor? 
Did you do additional steps to get this working?

If I test this code with my sensor, it only shows an update when I press the sensor's button.
When I 'trigger' the sensor, on Wireshark I do see the temperature and humidity attribute reports, but not the 65281 attribute report...

Would be nice to see if in this indeed also the battery level is reported, either as percentage or absolute value (between 2 and 3 volts)...

**Comment by TedTolboom** [comment]
Hi @rickardp, 
I've tested your approach throughout the day, but the sensor only starts reporting in the 65281 attribute around 30 minutes after initialisation and then typically every hour, or when the button is pressed. 

Even settings 'maxIntTemp' to 900 seconds, or triggering the sensor, does not result in additional temperature reports.. Do you have other experience?

**Comment by rickardp** [comment]
Hi @TedTolboom, thank you for the very informative answer! The solution to fix the mesh base code sounds like the correct way. My approach does indeed come with the price of quite poor report rate (once per hour sounds about right). For me that is quite acceptable, and something I would like configure anyway to conserve battery. When I put the sensor in the freezer I got a report within minutes, but that could have been pure luck, and I am not sure if it has a temp diff concept in the 65281 report.

**Comment by rickardp** [comment]
Sorry about closing and reopening, typing on my cell here :)

Just wanted to clarify that I am not configuring the sensor at all (at least that was my intent), since configuring the sensor causes an exception to be thrown somewhere in the Athom code (complains about the 65281 attribute missing).

**Comment by rickardp** [comment]
The temperature sensor in now working.

**Comment by TedTolboom** [comment]
Good to hear!
