### ISSUE TITLE
Xiaomi Aquara WXKG02LM scene allows only 1x click

### ISSUE THREAD

**Issue by Bhitv** [TedTolboom/com.xiaomi-mi-zigbee#105]
Hello Ted

I connected the double switch Xiaomi Aquara WXKG02LM to Homey.
The pairing went fine.
However, the scene in a flow allows only one click.
I have no choice to choose more than 1 click
I do have the choice of left, right button and both.
Switch disconnected and reconnected gives the same result.

O yes, and the device specifically in settings is blank, so I can not change anything

Thanks Bas

**Comment by TedTolboom** [comment]
@Bhitv please check the device capabilities at: https://github.com/TedTolboom/com.xiaomi-mi-zigbee/blob/master/README.md

For this device, if it has the Zigbee productID `Sensor.86sw2Un` this is the expected behavior / this device does not support any other options.

If this device has the Zigbee productID `remote.b286acn01` more options are supported.

**Comment by Bhitv** [comment]
You're right, it's the Sensor.86sw2Un.
I bought it last week and thought I would have the 2018 version.
I will ask the supplier how it is.
Thanks for your help.
Bas

**Comment by TedTolboom** [comment]
@Bhitv I would also have the same assumption.
I would contact the seller, but keep in mind, from the outside it is not possible to distinguish the different switches; they both share the same product number.

You could ask the question on the forum (app’s topic) at which seller they bought their switches

**Comment by Bhitv** [comment]
They are beautiful switches, and I can use them for my purpose.
But thanks for the advice, it will certainly do if I want to have more of it.
Bas

**Comment by TedTolboom** [comment]
accidentally re-opened I assume
