### ISSUE TITLE
Cannot connect Aqara Cube MFKZQ01LM

### ISSUE THREAD

**Issue by Svensson78** [TedTolboom/com.xiaomi-mi-zigbee#106]
Are there more people who cannot connect the Cube?
Sadly also not on the new version.

Adding takes about 10 minutes but then it is an unknown ZigBee device..

<img width="571" alt="schermafbeelding 2018-10-22 om 19 07 45" src="https://user-images.githubusercontent.com/44071424/47307155-9e735b80-d62e-11e8-9c8e-4252b56fc340.png">
<img width="563" alt="schermafbeelding 2018-10-22 om 19 13 31" src="https://user-images.githubusercontent.com/44071424/47307161-a29f7900-d62e-11e8-8839-af1e8c545e8d.png">

**Comment by Svensson78** [comment]
no one?

**Comment by chinswain** [comment]
Mine was a nightmare to pair, I ended up pressing the button repeatedly which seemed to do the trick. Before that I tried multiple times to pair the standard way (hold 5 seconds and release), has been fine since though.

**Comment by Svensson78** [comment]
> Mine was a nightmare to pair, I ended up pressing the button repeatedly which seemed to do the trick. Before that I tried multiple times to pair the standard way (hold 5 seconds and release), has been fine since though.

Thnx tried this but also without effect! Did it takes you also about 8 minutes to pair? Or is the sensor broke maybe.. Delete works fine grrrrr

**Comment by TedTolboom** [comment]
@Svensson78 Since you followed-up all known advices and it still shows up as unknown Zigbee device, it's likely the same issue as https://github.com/TedTolboom/com.xiaomi-mi-zigbee/issues/101 during inclusion the `productID` is not correctly captured during inclusion... and therefore the device is not recognized... 

Since the inclusion is handled by Homey's core (outside the app's core), I can't influence this issue myself. Sorry for that.

I'd suggest to contribute to this issue: https://github.com/athombv/homey/issues/2706
To raise Athom's awareness on this issue.

**Comment by vandernorth** [comment]
Tested on Homey 2.0.0, pairing with any Xiaomi device results in `status.invalid_setting_type`.
(Tested with motion sensor, door sensor, cube, double switch)

**Comment by JustThe2ofUs** [comment]
How many of the body sensors did you install? More than 3??
Here, 3 is the limit but door sensors and temp/humi sensors work fine.
