### ISSUE TITLE
Reports low battery on 2.0.0 rc

### ISSUE THREAD

**Issue by mhoogenbosch** [TedTolboom/com.xiaomi-mi-zigbee#110]
In firmware 1.5 there was no power or battery status available on the temperature sensor. Now it reports low battery, this is very annoying when connected with HomeKit. 

It also does not report temperature information to HomeKit, don’t know whether this is a app problem or homey itself.

**Comment by JustThe2ofUs** [comment]
After checking w/ Homey Support I can say It’s the app. Same here.

**Comment by TedTolboom** [comment]
Can you share a screenshot how this is shown in the v2 app? 
In the current App store version of the Xiaomi Zigbee app, the battery status is not reported for any device; also not for the temperature sensor; as indicated in the readme:

> Battery operated devices will not yet show the battery level; this will be added in a future release (manufacturer specific ZigBee implementation)

In Homey SW <1.5.13, due to the lack of a battery state: the battery icon was greyed out 

I guess in the V2 this is now shown as a low battery status; which is different behavior compared to 1.5.13.
Can you share a screenshot how this is shown; I'm currently running a different app version for testing.?
@JustThe2ofUs Can you also send the reference number of the Homey Support ticket.

It will be solved in the next update of the Xiaomi app, where battery reports will be enabled; showing the actual battery value

**Comment by mhoogenbosch** [comment]
Hi,


Ofcourse I can send an screenshot. The reference number of Homey Support ticket is 9617.


Screenshot 1 is the screenshot of the sensors device, this is the only thing that shows regarding to the battery:


[cid:79bbaedd-b523-4d15-95ee-35292aa74e80]

Screenshot 2 shows how this is shown inside HomeKit:


[cid:9ef5ab64-5486-464a-948b-46d5c08ecd15]

As you can see, all sensors are with exclamation marks which confuses the wife very much 😊.


I guess if you add the actual battery status it indeed is resolved. Any ETA on the update? Much appriciated!


Regards


Martijn Hoogenbosch


________________________________
Van: dT <notifications@github.com>
Verzonden: dinsdag 11 december 2018 13:51
Aan: TedTolboom/com.xiaomi-mi-zigbee
CC: mhoogenbosch; Author
Onderwerp: Re: [TedTolboom/com.xiaomi-mi-zigbee] Reports low battery on 2.0.0 rc (#110)


Can you share a screenshot how this is shown in the v2 app?
In the current App store version of the Xiaomi Zigbee app, the battery status is not reported for any device; also not for the temperature sensor; as indicated in the readme:

Battery operated devices will not yet show the battery level; this will be added in a future release (manufacturer specific ZigBee implementation)

In Homey SW <1.5.13, due to the lack of a battery state: the battery icon was greyed out

I guess in the V2 this is now shown as a low battery status; which is different behavior compared to 1.5.13.
Can you share a screenshot how this is shown; I'm currently running a different app version for testing.?
@JustThe2ofUs<https://github.com/JustThe2ofUs> Can you also send the reference number of the Homey Support ticket.

It will be solved in the next update of the Xiaomi app, where battery reports will be enabled; showing the actual battery value

**Comment by TedTolboom** [comment]
@mhoogenbosch thanks for reporting: briefly discussed with Athom, and this is a change in the apps-sdk.

Will be followed-up in: https://github.com/athombv/homey-apps-sdk-issues/issues/8

I'm testing the battery reporting at this moment. 

But also here, before a battery report is received, the alarm will first be triggered. So that is another reason to get this behavior solved.

**Comment by TedTolboom** [comment]
Fixed in app version 234
Also HomeKit should now show false state.

I will close this issue; if the problem still persists, please re-open
