### ISSUE TITLE
Error ‘status.invalid_setting_type’ Aqara Door Sensor

### ISSUE THREAD

**Issue by iformarco** [TedTolboom/com.xiaomi-mi-zigbee#143]
Evert time I try to install the Sensor, I get the same error. I tried to push the setup button every 2 seconds, but that didn’t do the trick...

**Comment by iformarco** [comment]
Same error with the vibration sensor...

**Comment by JustThe2ofUs** [comment]
Hiya. Check this. That is the only way it made me getting it to work. Ensure that the device is NOT aborting the pairing operation as described here:

https://github.com/TedTolboom/com.xiaomi-mi-zigbee/issues/117#issuecomment-461224521

**Comment by iformarco** [comment]
Already tried that. Didn’t solve the problem...

**Comment by TedTolboom** [comment]
@iformarco @JustThe2ofUs it turns out to be a bug at Homey side, incorrectly parsing an array with 1 element, in combination with a device not always reporting it's productID. aka rare issue.

I've just updated the app to v0.5.5 with the containment for this issue.

I'll close this issue for now (assuming solved), please re-open if still not solved when the app is updated to v0.5.5

**Comment by iformarco** [comment]
Ted: Thanks for the solution... It works great!
