### ISSUE TITLE
Again / Still: Sensors are not updating nor reporting 

### ISSUE THREAD

**Issue by JustThe2ofUs** [TedTolboom/com.xiaomi-mi-zigbee#148]
While the temp / humi sensors seem to be willing to send an update re: values once per month, the motion sensors do not recognise light correctly (4 lx is not really what the light is about ...)

This error is an Evergreen, isn’t it?

However - the sensors are useless as long as they’re just not working 🤷‍♂️🤨🤮😣

**Comment by DiedB** [comment]
Experimented with some motion sensors yesterday. Motion seems to work fine. Luminance is slow and seems to only update once motion is updated. I have been away from home for 10 hours now, and the luminance hasn't updated since.

I have a lot of programming knowledge and would like to help, if you could give me some pointers.

**Comment by JustThe2ofUs** [comment]
Hiya; dunno what’s going on as the issue is existing since months now. I feel like he could really need your help as he doesn’t get it handled.

**Comment by DiedB** [comment]
I did some research on the topic and it does not seem to be an issue on the Xiaomi side, as the sensors should be sending a report to Homey on every change of measurement.

I have a temperature/humidity sensor in the bathroom (for ventilation mainly), which is working fine. I've been away from home for a few days and it keeps reporting all its measurements correctly. Is your sensor not doing this correctly?

My motion sensors have stopped reporting since I left home. Insights graph just stays flat on the last value.

I cannot find any direct problems with the code of this app that should be causing it (although I have no clue on how the ZigBee part of Homey works).

**Comment by JustThe2ofUs** [comment]
Hiya;
As the App supports a ton of devices and thousands of users seem to use it, I can imagine that maintaining such an App is like a fulltime job! 
If it sounds like being harsh sometimes - sorry -
It’s just that when the sensors don’t work correctly - the whole Homey System to me is not that good working as the main flows just don’t work. 
However - I am not that firm w/ the IT behind but perhaps a log could help to see what’s wrong?

**Comment by JustThe2ofUs** [comment]
Any news on that one here? I personally am very sorry but feel very annoyed as the app causes the sensors to just not work. 🤬

**Comment by JustThe2ofUs** [comment]
Hiya. 
Seems like I’m repeating myself but:
Any news on this?! 
The devices are just useless 🤷‍♂️

**Comment by JustThe2ofUs** [comment]
Up.
