### ISSUE TITLE
Aqara temperatire sensor not updating

### ISSUE THREAD

**Issue by cmd85** [TedTolboom/com.xiaomi-mi-zigbee#154]
Hello,
i just booted my homey yesterday and added my sensor.
Worked fine for a few hours but now it havent reported anything for 11 hours.

Not sure how to go forward, can i set the update frequence somewhere or is there a way to see if its to far away?
But if its to far away shouldnt homey report it as "missing" or something.

**Comment by JustThe2ofUs** [comment]
Hiya;
This seems to be a well known issue with Homeys Zigbee-Core, so nothing to do w/ the App itself. Unfortunately „all we can do is sit and wait“ 🎵 ... but it might be very helpful and increase speed of fixing if you could pls report this error to Athom Support as a request. So did I and some others as well.

**Comment by ogrosko** [comment]
Can confirm same behaviour. And same problem I had with OpenHAB. 
Read somewhere it is xiaomi issue to prevent using it with other brands :(

**Comment by JustThe2ofUs** [comment]
Hi Ted. 
Can you give a brief update re: this issue as it seemed to require major changes of Athom in the Zigbee-Core?!

**Comment by shaarkys** [comment]
What is interesting - in my case sensors were not updating like for month - after waking them up, again for few hours only. I purchased ZigBee repeater and since then it seems to be much better - seems the sensors are working now for 14 days in a row, which is my personal record. Would be as well interested on what is causing this, as other sensors (eg. Motion), located same place, are and were fine.

**Comment by cmd85** [comment]
I got a repeater very close to the sensor and it still fails after a few hours. 
It's weird since my other aqara sensors on my doors works perfectly fine, same distances or even longer away. 

But both aqara temperature sensors fail, not sure if it's different types of protocols within zigbee they use.

**Comment by shaarkys** [comment]
Also interesting, those sensors not updating in the past are now connected within mesh using more nodes as per https://developer.athom.com/tools/zigbee - so try to check this one

**Comment by shaarkys** [comment]
![obrazek](https://user-images.githubusercontent.com/14859895/63406862-60c89600-c3eb-11e9-95a5-40d9575c35dc.png)

**Comment by shaarkys** [comment]
Those three had problems in the past...now with Ikea ZigBee repeater looks much better.

**Comment by cmd85** [comment]
Actually checked that page now and saw it had more , and also checked the sensor now and it has started updating . 

Tbh I haven't checked it in a month since I haven't heard anything new around this :)

Insights tells me it's working since July now which is great ! 
Maybe it was around that time I installed the door sensor close to it.

**Comment by shaarkys** [comment]
Actually my experience was, that after installing repeater, it took several hours to get it really reflected. 
Just what was also key was the right placement of the repeater itself.

**Comment by JustThe2ofUs** [comment]
When placing a Zigbee router (which is usually ridiculous as the App and Homey are dedicated to to exactly THAT) Homey needs a cold restart. Just then the mesh gets re-created and the repeaters get involved. 

Honestly - dunno what I can do more than just asking here and in the forum but it doesn’t seem that anything happened here since 4 months. At least a comment would’ve been - well - adequate, wouldn’t it?! 
It might make sense to just kick xiaomi stuff to the bin...
