### ISSUE TITLE
Issue after restart homey

### ISSUE THREAD

**Issue by seblang** [TedTolboom/com.xiaomi-mi-zigbee#160]
882bd654-9e4d-40dc-8446-b68278c99a56

**Comment by TedTolboom** [comment]
You’ll need to provide a more accurate issue description, because the provided description and log does not show anything:

A crash occurred for your app (version 0.5.5) at Aug 6, 2019 6:53 PM (UTC).

Homey software version: 2.5.0

Crash report: 

Note: this log has been manually submitted by a user. Log ID: 882bd654-9e4d-40dc-8446-b68278c99a56 User Message: Issue after restart homey box 
 ---- stdout ---- 

 ---- stderr ----

**Comment by TedTolboom** [comment]
will close the issue pending user feedback
