### ISSUE TITLE
Round temp/hum sensor not working

### ISSUE THREAD

**Issue by Dgh1974** [TedTolboom/com.xiaomi-mi-zigbee#162]
Updates after adding for 15 to 30 mins. After that once a day when lucky. Pressing the button i have an instant update in homey.

I contactet athom butvthey claim its a bug in the app.

**Comment by JustThe2ofUs** [comment]
Yeah; it’s the same old game since 6 months now. 
People here claim again and again that it’s a big of the App; Ted keeps telling it’s a big of Athom; Athom then says again it’s an issue of the App. 

In the end it’s as usual: the customer is the idiot.

**Comment by ronald2404** [comment]
I assume this is al related to the required Zigbee rewrite we are all waiting for..

**Comment by TedTolboom** [comment]
@Dgh1974 What you could do (long shot) is putting the sensor close to Homey, restart the app and keep pressing the button every 10 second for the first 2 minutes. It might be that the attribute reporting, determining the normal frequency of reporting, is not properly set.

If that is not working, then it is indeed a Zigbee networking issue, ie. loosing connection is one of the stability issue that are outside my control (Zigbee Network behavior) that hopefully is fixed in the Zigbee rewrite Athom is working on.

**Comment by TedTolboom** [comment]
@JustThe2ofUs you're dangerously close to what I can and will accept.
Please contribute in an open and contributing way!

**Comment by ronald2404** [comment]
Thanks for your support Ted, ill try that and else ill keep spamming athom :-) Cheers!

**Comment by TedTolboom** [comment]
Looking forward to your feedback @ronald2404

**Comment by JustThe2ofUs** [comment]
@tedtolboom
You’re absolutely right. I am very sorry about this. I’ve been so f*^* up as the sensors issues killed a ton of routines many times that I completely forgot to settle my southern temperament appropriately. 

Keep up the good work and the support you provide!

**Comment by ronald2404** [comment]
HI Ted, unfortunate it didnt solve my issue. Ill ask @thome for an update
