### ISSUE TITLE
Xiaomi / Aqara ZigBee problem after Homey update 2.5.2

### ISSUE THREAD

**Issue by andeno** [TedTolboom/com.xiaomi-mi-zigbee#166]
After Homey update 2.5.2 tonight, the Aqara Wireless Switch Double (2018) is not working. I also have a Wireless Switch which however still works. Thanks

**Comment by satoer** [comment]
Same here. 3 motion sensor's stopped working / updating brightness information after update 2.5.2 (other same sensors work fine)

**Comment by FrankBakermans** [comment]
Same for me, mini switches, door contacts and motions sensors don't work anymore after the homey update

**Comment by JustThe2ofUs** [comment]
Did you try the following:

1. Take Homey off power for 20 min and then put back on power again (=force mesh to re-build)

2. Remove devices from homey and re-add

**Comment by FrankBakermans** [comment]
Hi,

I tried, first it was very difficult to remove the devices and I cannot re-add the devices. The process times out.

**Comment by tranceblast** [comment]
I have the exact same problem with a lot of my Aqara motion sensors. Sometimes the sensor won't react and sometimes it does. I have tried to remove some sensors and ad them again but it's still the same. Sometimes it help to push the button och sometimes it won't and then I have to remove the sensor and ad it again. Have all my sensors problem or is it the app or homey? 
PTP won't help...

**Comment by satoer** [comment]
Ive removed the sensors, and added them again, and that seem to do the trick to fix the problem. But it's a big hassle because every flow that uses them needs to be fixed also.
After a couple of day's some other sensors failed / got stuck (door and window sensors). This time I could regain connection by using a PTP (Pull the plug) reset. I've also added a couple of sensors last couple of day's, maybe that's under the influence also.

**So, malfunctions that happened:**
Failed updating from motion and door/window sensors

**Things that's have been change in my setup before / during this malfunction:**
Homey updated to 2.5.2
Added sensors to my setup

**"Solutions":**
Remove the device and re-add them
PTP (Pull the plug) reset (I waited 5 minutes)

**Comment by ronniham** [comment]
Yesterday ive bought a homey early 2019 and have 5 motion sensors from Aqara. None of them will connect. Homey is fully updated and had yesterday the last update available.

**Comment by JustThe2ofUs** [comment]
Well, this forum is kinda dead and it’s with Zigbee since 8 months as follows:

• Devs will you it’s all Athoms fault and there has to be a complete new rewrite of its Zigbee core (see e.g. Gledopto App or this Xiaomi App here)
• Athom will keep claiming it’s not their fault

In the end you will end up w/ a device that’s kinda nice to play with, but you won’t get any support that will fulfil your expectations, perhaps.

-- // via mobile //
Am 31. Aug. 2019, 11:11 AM +0200 schrieb ronniham <notifications@github.com>:

**Comment by TedTolboom** [comment]
@JustThe2ofUs thanks for summarizing. 

Athom is working on the Zigbee rewrite. Stability issues I can't control nor influence from within the app.
