### ISSUE TITLE
Aqara temperatuur sensor

### ISSUE THREAD

**Issue by roellie** [TedTolboom/com.xiaomi-mi-zigbee#178]
Hallo,
Graag zou ik meteen na het openen van de Homey app de temperatuur (op dat moment) in het witte vierkantje van de AQARA TEMPERATUUR sensor zien!
Is dit te realiseren?

Groeten Roel

**Comment by TedTolboom** [comment]
Hi Roel,
Sorry, this is not possible / not an option I can use for a temperature sensor that is provided by Athom. This is only possible for the setpoint of a thermostat (automagically done).

Please request this at Athom support; there are more people requesting this.
Will close this issue, since not able to solve.
