### ISSUE TITLE
Homey Version 1.0.4

### ISSUE THREAD

**Issue by woodiewales** [TedTolboom/com.xiaomi-mi-zigbee#22]
Hello,

I tried to install the Xiaomi App, however it is telling me that it is not compatible with my version on Homey 1.0.4 . Will there be an update to make it compatible?

Many thanks
Rob

**Comment by TedTolboom** [comment]
@woodiewales the Xiaomi ZigBee app has a dependency to require Homey SW 1.5.4 minimum; because this version incorporates the required ZigBee changes to make the Xiaomi devices operational.

So it will not be able to create a version of the app for the 1.5.3 Homey SW version.
I would have expected that 1.5.4 (or a higher version) would have been released to Stable earlier, but that has not been done by Athom
 
Currently 1.5.6-RC8 is released to experimental channel, no timing is available when a next version will be released to Stable.

I expect that this is addressing your question and will close this issue.
If not, let me know.
