### ISSUE TITLE
Support for New Set of Aqara D1 Wall Switches 

### ISSUE THREAD

**Issue by JohnLCK** [TedTolboom/com.xiaomi-mi-zigbee#239]
Hi Ted & Team,

I noticed Aqara launched a new set of wall switches and believe most people are buying those now and they stopped production for the older models. I just tested it on my Homey and it doesn't seem to work. It states that it only recognises it as a basic zigbee device. Would like to check any plans to include support for the latest set of wall switches? My switch model is QBKG22LM (double trigger, non-neutral). Appreciate your help. Cheers!

Warm regards,
John

**Comment by TedTolboom** [comment]
@JohnLCK they are supported in the Homey v5 compatible version: https://homey.app/nl-nl/app/com.xiaomi-mi/Aqara-&amp;-Xiaomi-ZigBee/test/

Unfortunately, it is not possible to release an app update to the app store for Homey v4 when a test version for Homey v5 is available due to limitations of the app store itself.

Hope to have answered your question, I'll close this issue. If not, please reopen
