### ISSUE TITLE
 Can not add the app to homey

### ISSUE THREAD

**Issue by PeterR1975** [TedTolboom/com.xiaomi-mi-zigbee#248]
Hello Ted,
When i wanna download the app from the homey appstore i get a fault message that says “ incompattible app-version” any adea how i can solve this and download the app?

with kind regards,
Peter

**Comment by TedTolboom** [comment]
Hello Peter,

I suspect that you are running the Homey v4.2 version.
Due to limitations of the Homey apps store, I can only have 1 version released to the App Store.

Since 95% of all Homeys have Homey v5 installed, as per guidance of Athom, I have released the v1.2.5 version of the app, compatible with Homey v5, to the App Store.

There are two options to resolve:
1. Update your Homey to Homey v5, then install the app. Would be my recommendation due to the Zigbee improvements (function and stability)
2. If you choose to keep Homey v4, it is possible to still download the v0.8.0 version of the app from GitHub and install it through the commandline interface (CLI)

If 2. Would be your preference, I can point you to the right locations

**Comment by PeterR1975** [comment]
Hello Thanks for your answer that was indeed the problem. After update it works.
Thanks a lot i wil donate

**Comment by TedTolboom** [comment]
Your welcome! And much appreciated!
