### ISSUE TITLE
Implement battery status reporting

### ISSUE THREAD

**Issue by JohanBendz** [TedTolboom/com.xiaomi-mi-zigbee#25]
Does the battery operated devices support reporting battery status? If so, can this information be added to the app abilities?

**Comment by TedTolboom** [comment]
@JohanBendz yes, most of these devices report their battery status.... but not in the standard ZigBee reporting... but in it's lifeline reporting.

Example of the Cube:
```
2018-01-04 20:05:22 [log] [ManagerDrivers] [cube] [0] report { event: 'report',
  token: 'a8ca1a8f-838c-4e01-aa31-3de472bfa9b0',
  device: '0x00158d00010df310',
  endpoint: '1',
  cluster: 'genBasic',
  attr: '65281',
  value: '\u0001!�\u000b\u0003(\u0014\u0004!�\u0013\u0005!�\u0000\u0006$&\u0000\u0000\u0001\u0001\n!\u0000\u0000�!\u0000\u0000�!�\u0000�!z\u0000�!\u0003\u0000' }
```
I do need to find a way to extract the Battery value out of this reported string...
For all battery devices, the battery capabilities have been added, so that adding battery reporting will only be a app (driver) update and to prevent that users need to remove the device to add the battery capability (current Homey limitation to only be able to add capabilities during inclusion).

**Comment by TedTolboom** [comment]
Leading Athom issue: https://github.com/athombv/homey/issues/2165

**Comment by JohanBendz** [comment]
Hi there Ted, noticed a solution to reading out the battery value in a SmartThings GitHub thread, perhaps this can help you out? https://github.com/bspranger/Xiaomi/blob/master/devicetypes/bspranger/xiaomi-aqara-button.src/xiaomi-aqara-button.groovy

**Comment by rickardp** [comment]
What do we need from Athom? AFAIK, I already parsed that struct (see the now closed PR here https://github.com/TedTolboom/com.xiaomi-mi-zigbee/pull/11/commits/6fae2aa170bcd3d39ad12b5a899b5b6ab11243f0)

I experimented with reading battery values back then, but I never took the time to figure out the unit (from @JohanBendz  comment I now know though...)

Maybe I am missing something, or why do we need a rawValue field when we already get the data in the value field, converting it to a byte buffer seem to work?

**Comment by TedTolboom** [comment]
@rickardp good point; well taken...
In the past I removed this reportListener, since the issue with the  primary reportListener was solved and providing more data points...

Based on your feedback I've been experimenting with this approach on the Cube and Aqara temperature and Humidity sensor.... with a green (filled) box in the top left corner...
![image](https://user-images.githubusercontent.com/17163431/36833933-6915d91a-1d31-11e8-8967-2b30cf9b5a9e.png)

with the lifeline report, also other data is provided... which I would like to include..
I'll be updating device by device (will need some tweaking per device)... Battery-powered sensors first..

Thanks once more!

**Comment by TedTolboom** [comment]
Well, @rickardp after quite some time debugging this weekend... I'd like to come back to your questions:

> What do we need from Athom?
> or why do we need a rawValue field when we already get the data in the value field, converting it to a byte buffer seem to work?

Yes, we do get the data in the value field in the device driver and converting it to a byte buffer seems to work... at first sight... 

But not all data, and in particular the battery values, are giving valid data..
It turns out that the value string, as provided to the device driver has been UTF-8 encoded... 
which is malforming the HEX data and resulting in that the byte buffer as converted in the device driver is not representing the HEX data as provided by the actual device itself (as seen in sniffer data)... 

For more details: see https://github.com/athombv/homey/issues/2165#issuecomment-370257546

Likely, due to the value range of the temperature and humidity, the UTF-8 encoding did no damage to these value segments...

So we do need to get the raw (not UTF-8 encoded) data available in the device driver to be able to implement battery reporting.... I manually checked the HEX streams as captured by the Zigbee sniffer and the data is there...

**Comment by TedTolboom** [comment]
I inquired for an update at Athom (Emile in person) on what the plans are to complete the Zigbee implementation (and thereby resolve this issue)...

After an extensive discussion to triggered by this question, all I got back was:

weejewel [12:43]
OK! Well, we're working on it slightly_smiling_face

So unfortunately, I cannot provide a more detailed response to my app users.
If you have questions when this will be resolved, please contact Emile directly on slack or by mail....

**Comment by BBEHannes** [comment]
how is this going? I still do not see the battery level of several Xiaomi sensors (aqara door\windows and Motion sensors)

**Comment by chinswain** [comment]
@BBEHannes Unfortunately Athom need to make a change - I've hassled them a few times about this but they don't seem interested...

**Comment by BBEHannes** [comment]
sigh...

**Comment by jwikman** [comment]
Does FW2.0 support the complete Zigbee implementation? Maybe this is solvable now?

**Comment by lucasvdh** [comment]
Did anyone look into if the v3 firmware fixes the issue preventing the implementation of this?
