### ISSUE TITLE
Aqara Motion P1 - problems using "Motion sensor blindtime" and "Reset motion alarm after"

### ISSUE THREAD

**Issue by MojoDK** [TedTolboom/com.xiaomi-mi-zigbee#311]
It looks like that Shelly Motion "blind time" is a count down until motion deactivaded event fires ... like 1 minute - and if motion is detected before the count down reaches 0, the timer is reset (goes back to 1 minute).

I can't archive this in P1. 

I've made som tests and I can't see "Motion sensor blindtime" does anything.

"Reset motion alarm after" is the countdown ... but no matter if I move during the countdown, the countdown is not reset. So if I set my P1 to "Reset motion alarm after" to 1 minute - no matter how much I move during this minute, deactivated event is fired. If I move during the countdown, I want "Reset motion alarm after" to be reset to yet another minute.

Am I missing something here?

**Comment by TedTolboom** [comment]
Motion sensor blind time is defined as: "This setting determines the period of time through which the PIR sensor is “blind” (insensitive) to motion."

Motion alarm reset time: "This setting will disable the motion alarm after the given time (in seconds) has expired. Every time motion is observed by the device it will reset this timer."

I could update the help text as: "This setting will disable the motion alarm after the given time (in seconds) has expired. Every time motion is observed by the device **(outside the blind time)** it will reset this timer."

See below loggings to illustrate:
```
[log] 2023-01-29 11:53:03 [ManagerDrivers] [Driver:motion.ac02] [Device:215dc75c-6cc7-4aa8-9bff-2ea16e0b776a] handle report (cluster: OccupancySensing, attribute: -, capability: alarm_motion), parsed payload: n/a
[log] 2023-01-29 11:53:03 [ManagerDrivers] [Driver:motion.ac02] [Device:215dc75c-6cc7-4aa8-9bff-2ea16e0b776a] handle report (cluster: IlluminanceMeasurement, attribute: measuredValue, capability: measure_luminance), parsed payload: 45
[log] 2023-01-29 11:53:37 [ManagerDrivers] [Driver:motion.ac02] [Device:215dc75c-6cc7-4aa8-9bff-2ea16e0b776a] handle report (cluster: OccupancySensing, attribute: -, capability: alarm_motion), parsed payload: n/a
[log] 2023-01-29 11:53:37 [ManagerDrivers] [Driver:motion.ac02] [Device:215dc75c-6cc7-4aa8-9bff-2ea16e0b776a] handle report (cluster: IlluminanceMeasurement, attribute: measuredValue, capability: measure_luminance), parsed payload: 63
[log] 2023-01-29 11:54:38 [ManagerDrivers] [Driver:motion.ac02] [Device:215dc75c-6cc7-4aa8-9bff-2ea16e0b776a] manual alarm_motion reset
```
My blind time is set as 30 seconds and cancellation time is set as 60 seconds
At 11:53:03 I triggered a motion, which is detected and triggered the motion alarm
At 11:53:25 I again triggered a motion, which is not detected because it is in the blindtime
At 11:53.37 I again triggered a motion, which is detected because it is outside of the blindtime
At 11:54:38 the motion alarm is reset, based on the set duration of 60 seconds after the re-trigger of the motion.

I hope this clarifies your question.

I will add an additional check that setting the reset duration below the blind time will result in an error.
