### ISSUE TITLE
Support multiple clicks + hold/release for Aqara Wireless Remote Switch Single / Double

### ISSUE THREAD

**Issue by jnwllm** [TedTolboom/com.xiaomi-mi-zigbee#37]
Apparently it should be possible (@TedTolboom ) to support more than on/off for the Aqara Wireless Remote Switches by implementing this driver-side. I would really appreciate this feature to control multiple scenes and dimming of my Fibaro powered RGBW LED strip on the attic.

**Comment by moekdegroot** [comment]
Hi Ted,
Thanks for the app, truly awesome!
Just wanted to create an issue that 2,3,4 clicks isn't working for my aqara wireless single switch although it's available in the flow editor.
I'm a little confused, did you implement it already and it just isn't working?
If that's the case, you need help testing?
And just to check, we are talking about [these switches](https://xiaomi-mi.com/sockets-and-sensors/aqara-smart-light-wall-switch-single-key/), right?
Best, Moek

And in case you need it:
![aqara](https://user-images.githubusercontent.com/16590284/36060563-93d2f9c4-0e4c-11e8-9bb5-2a25b87759c3.png)

**Comment by moekdegroot** [comment]
Hi @TedTolboom , 

Can I bother you for an answer to my question above?
As I said above I installed an aqara single wireless switches and have the option to select 1, 2 ,3 and 4 clicks in the flow editor but only 1 click is working.
Because the app description in the app store only mentions 1 click (and combined click) I’m not really sure what to do next.
Did you implement the 1-4 clicks as the OP mentioned/asked for, or did I find a bug?
I would like to create an issue for my situation but I don’t know how to classify it.
1. I have flow options that shouldn’t be available (bug?)
2. missing device id causing the flows not to work.

Hope you find the time to answer so I can create the issue.

Best, Moek

**Comment by TedTolboom** [comment]
Hi @jnwllm, thanks for informing that the trigger card of the Single version is showing incorrect (unsupported) options. In the next update, I'll remove these unsupported options first...

I'll keep this issue option, as feature request to extend support to multiple clicks.
Please note, that hold and release will not be possible on this device. Since holding the button, will trigger the reset / inclusion option of the device

**Comment by jnwllm** [comment]
Haha, I was not aware that the release made it look like it was possible. I was hoping that you would make it possible instead ;-) But I understand that that's the reason why you keep this issue open. I'd love to hear if more people are interested in this feature and if it's going to be developed any day.

**Comment by Zignature** [comment]
I would to have double click option :)

**Comment by Zignature** [comment]
In the meantime I found it the 2018 version does support it by means of "activated scene".
