### ISSUE TITLE
Enhancement request: Add a "Last signal received" attribute

### ISSUE THREAD

**Issue by jwikman** [TedTolboom/com.xiaomi-mi-zigbee#40]
I don't know if this is techically possible, but it would be great to know when Homey last received a signal from a device. 
It should be shown in the "Device information" section on the device settings page.
It should also be a tag on the device that could be read in a flow.

In that way I could create flows that checks the health of my devices.
One additional feature would be a trigger on "Last signal received changed", but it's not as much needed as the other... But if I also get that, I could create my own alarm when it's been to long since a signal is received.

The reason behind this request is that I've got some Xiaomi sensors that sometime stops to send signals (or if it's Homey that stops to receive them, I don't know). If i go and click the button on the device it kicks in again. But now this is a manual check through Insights, and I would like to automate this.

**Comment by MagnusPer** [comment]
Would be great to have this "status" information together with the temperature value. This Because there might be several hours the value was updated. Before when used Telldus plattform this information was available (see [this](http://nytestat.se/telldus-v2-gor-433-mhz-dubbelt-sa-anvandbart/) example)

**Comment by TedTolboom** [comment]
@jwikman @MagnusPer thanks for the feedback.
I understand the request, but as app developer I'm not able to add information in the "Device information" section. In addition, I'm think the new Homey app will have this option enabled for all devices... it currently shows in the device details: "Turned on since 13:37"...

So, I'll check with Athom whether this indeed will be implemented by default into the new Homey app.
If so, I will not implement this from app side.

An alternative option would be to use the generic devices card:
<img width="293" alt="schermafbeelding 2018-03-05 om 21 56 38" src="https://user-images.githubusercontent.com/17163431/36999494-8d3e14f0-20c0-11e8-88cb-2593c0d7b09c.png">
Which should provide a list of devices that have not reported in in e.g. a day...

**Comment by jwikman** [comment]
@TedTolboom agreed, it would be better if Athom makes a generic implementation of this.
This information is superior to the "device hasn't reported"-flow (using that since a few weeks back), since you can quickly see on the sensor if you can rely on the values shown. As today those values can be real old without you knowing that...

**Comment by robertklep** [comment]
As an intermediate solution, would it be possible to add a "Last Seen" item to the device's mobile card? Similar to what MySensors shows:

<img width="330" alt="screen shot 2018-03-18 at 18 51 44" src="https://user-images.githubusercontent.com/1190916/37569076-9c44bd38-2add-11e8-902a-e541debe4f0a.png">

**Comment by jwikman** [comment]
@TedTolboom I've added a "Last Seen" read only setting (Label) in the "Device Specific" section for the sensors "sens" and "weather". That's enough for me right now, but it would be more elegant to implement it as a capability, as suggested by @robertklep. But I'm too new to this to be able to pull that off.

Anyway, let me know if you want me to create a Pull Request and I'll try to figure out how to do that. :)
And if the approach seems fine, I could implement it in the other sensors as well.

At least I'm happy with this feature, now I know if I can rely on the values shown.
