### ISSUE TITLE
New Aqara Wireless switch WXKG12LM with gyroscope?

### ISSUE THREAD

**Issue by LyoshaDovolen** [TedTolboom/com.xiaomi-mi-zigbee#42]
Aqara Wireless switch WXKG12LM with gyroscope? New model button (is defined as lumi.sensor_switch.aq3) with signal "shake"

https://github.com/bspranger/Xiaomi/issues/106#issuecomment-369412141

**Comment by LyoshaDovolen** [comment]
https://github.com/bspranger/Xiaomi/issues/106#issuecomment-369412141

**Comment by TedTolboom** [comment]
Hi @LyoshaDovolen,

Thanks for reporting... if a new Xiaomi device will be added to the ZigBee range, I will add it to the app.

I will need to get my hands on one of these devices in order to define the device driver. Likely it will be a combination of the current Aqara Wireless Switch and the gyroscope function of the Cube...

Only problem is that I can't seem to find a store that is clearly indicating the version.
Do you have this device already? Did you find a store that is selling this specific version?

**Comment by LyoshaDovolen** [comment]
That's all I could find:
http://allegro.pl/aqara-mini-przelacznik-bezprzewodowy-naklejka-mg-i7186033766.html
http://mall.iqiyi.com/item/19rrnomm40?odfrm=so
http://item.jd.com/5273039.html

**Comment by TedTolboom** [comment]
Received the new Aqara Wireless Switch with Gyro...
Will add support in the next update

**Comment by TedTolboom** [comment]
See release v0.3.0 -> added support for the Gyro version
