### ISSUE TITLE
[Request] Flowcard "Motion alarm has changed"

### ISSUE THREAD

**Issue by StraDijk** [TedTolboom/com.xiaomi-mi-zigbee#53]
Would like to have a flowcard with "The motion alarm has changed".

It would reduce the amount of flows i use for turning lights on/off.

**Comment by TedTolboom** [comment]
Hi @StraDijk,

I completely understand the request, which is similar to another request from to have a flowcard for open / close: https://github.com/TedTolboom/com.xiaomi-mi-zigbee/issues/44...

For the Xiaomi app, I use as much as possible the default available flow cards; which are linked to a capability and made available by Athom in Homey's core (to secure the same look and feel)..

As also explained in that issue, I'm a bit reluctant to create a custom flow card from within this app... because the next question will be to also do this for all other apps...

It's an improvement that Athom will need to implement, so that it becomes available for all apps...

Can you create an issue at https://github.com/athombv/homey/issues/ or contribute (extend the request) to the issue on open/close: https://github.com/athombv/homey/issues/2296 ?

I'll close this issue in the meantime... if you disagree, please let me know.

**Comment by StraDijk** [comment]
Yup, that is the same thing.. Thanks
