### ISSUE TITLE
Mesh issue

### ISSUE THREAD

**Issue by Rockhoppers1964** [TedTolboom/com.xiaomi-mi-zigbee#55]
My Zigbee setup does not appear to be forming a mesh network and the range to some devices as very poor. Is this function enabled within the product range ?

**Comment by kasteleman** [comment]
First, do you only have battery powered devices?
Second, please give Some more details regarding the devices you have

Op za 31 mrt. 2018 om 13:27 schreef Rockhoppers1964 <
notifications@github.com>

**Comment by Rockhoppers1964** [comment]
I have a bank of three double mains Xiaomi wall switches.
Two of them work most of the time, one sometimes.
I can sit and switch 1 and 2 off and on ok using Homey, but Number three will not respond.
they are within inches of each other so don't think it is range, unless interference.
I have removed and re-added the unit twice now with no change
Also, the whole Zigbee network appears to be connected to Homey directly, and not through a mesh like ZWave. Is this normal ?

![image](https://user-images.githubusercontent.com/37954974/38162785-976e44e4-34df-11e8-9f34-0f28d37309c1.png)

**Comment by Rockhoppers1964** [comment]
![image](https://user-images.githubusercontent.com/37954974/38162790-a6a2f874-34df-11e8-9696-a31a5571466b.png)

**Comment by kasteleman** [comment]
Within inches?

What if you move the 3. To another location? Does it respond then?

Op za 31 mrt. 2018 om 13:33 schreef Rockhoppers1964 <
notifications@github.com>

**Comment by Rockhoppers1964** [comment]
There a three doubles right next to each other, two work, one does not.
Have not tried moving it yet.
Have another one 4 meters from Homey in the other direction and even it is a bit flaky at times.

**Comment by Rockhoppers1964** [comment]
In the bank of 3 units set up at 3,2,1, with 3 being furthest away by 6 inches, 1 and 2 work, 3 sometimes, but more often not ?

**Comment by Rockhoppers1964** [comment]
Also have a Human body sensor another 6 meters away through a wall and it has never responded.
I assumed it would mesh to the mains wall switches

**Comment by TedTolboom** [comment]
@Rockhoppers1964 it should start creating a mesh... 
however there are multiple issues reported about the stability of Homey's Zigbee network..

Also in the latest Blog post, Athom indicated that zigbee might be unstable with xx devices:
https://blog.athom.com/behind-magic-march-2018/

And corresponding issues:
https://github.com/athombv/homey/issues/2325
https://github.com/athombv/homey/issues/1956
https://github.com/athombv/homey/issues/2141

At this moment, I can't futher troubleshoot this issue (due to lack of logging capability).

**Comment by Rockhoppers1964** [comment]
Nope, still not seeing the mesh yet.
Loosing the Zigbee units a few hours after a restart.
A

------ Original Message ------

**Comment by TedTolboom** [comment]
@Rockhoppers1964 as mentioned in https://forum.athom.com/discussion/comment/71694/#Comment_71694, I understand that the installation of the new app update resulted in a re-meshing / re-establishing of Zigbee routes.

Since no relevant changes were made, only the re-initialisation of the app resulted in this....
Will take that one into consideration for other issues...

Can you show how the Zigbee network now looks like?

**Comment by Rockhoppers1964** [comment]
![capturez](https://user-images.githubusercontent.com/37954974/39696440-a68f432e-51e5-11e8-8cdc-72f5b5e8d01e.JPG)

Appear to be forming a mesh now.

**Comment by TedTolboom** [comment]
@Rockhoppers1964 based on the network table shown above, it still shows the direct connections between the device and the ID of Homey (0)... 

so not really a mesh yet; in that case, it would show a route from endDevice via Router to Homey..

What happens when you wake-up one of the EndDevices? Ie press the button of the Aqara Human Body sensor....

**Comment by jtebbens** [comment]
Latest firmware on homey 1.5.11. Ikea lightbulb E27 (zigbee router) do not mesh up together. I have a top floor that homey cannot reach. I have 2 others (voorraad kast and toilet 1st floor) that could be in between as router. It jus doesnt create a mesh. Now moved 2 of those to my philips hue and now the top floor lightbulb responds. I tried only the topfloor first but that didnt work, then the toilet was added to philips hue and they interconnect. For now I have a workaround to a working light upstairs that homey could not mesh based on Ikea router based bulbs.
