### ISSUE TITLE
Enhancement request: aqara human body sensor

### ISSUE THREAD

**Issue by andydp84** [TedTolboom/com.xiaomi-mi-zigbee#59]
I just added one human body sensor to my network which works better than Fibaro's/Neo Coolcam's motion sensor. I made two flows; one to switch on the light if the senor is triggered and one flow that switches off the light when the motion alarm is switched off.
A major issue here is that the light will be switched off after the amount of seconds you entered in the device settings (e.g. 60s). Even if you're still moving in the room the light will switch off after x sec and switch back on a second or so later because the motion alarm is triggered again. Which is annoying all the time.
Could you add a parameter that keeps the motion alarm on (so resets the timer) when motion is detected during the "motion alarm on" phase? Fibaro, Neo Coolcam and other motion sensors all have this feature.
Thx!

**Comment by TedTolboom** [comment]
Did you only try with the 60 seconds or also with other (bigger) values like 90 seconds?

The requested feature is already part of the code... implemented on driver side, since the device doesn’t cancel the alarm trigger itself..

but please be aware that in normal operation mode (as the device will automatically enter 2 hours after inclusion), the device will only re-trigger after 60 seconds...

Hence the lower limit of the reset time.
It might be the case that if you use the 60 seconds that the two events trigger just in the wrong order... can you check with a cancellation one bigger than 60 seconds?

**Comment by andydp84** [comment]
I changed the parameter to 70s but with no result. Lights are switched off after 70s even if I moved like hell in front of the sensor.
Increasing the time limit even further seems a waste of energy to me if the sensor should trigger lights (I don't want the lights on for 60+ seconds if I'm just passing down the hall.)

Do you see a solution for this issue?
