### ISSUE TITLE
Mesh driver does not work

### ISSUE THREAD

**Issue by calambur** [TedTolboom/com.xiaomi-mi-zigbee#66]
Mesh driver does not work Therefore, in the remote ends of the house, Homey does not see the device. 
![2018-05-12 15 05 09](https://user-images.githubusercontent.com/1989503/39957126-0690ed9a-55f6-11e8-96a0-811347d88a5b.png)

**Comment by permadm** [comment]
+1

**Comment by Romast-Kirov** [comment]
@calambur @permadm 

Привет!!!
На сайте девелопера не всегда правильно отображается как подключено устройсвто.
Недавно я столкнулся с такой же проблемой.
Решил так.
Подключил все устройств к Homey  и затем разместил их в своих местах, там где   они должны работать через роутер. 
А затем на каждом устройстве несколько раз нажал на кнопки для соеденения, что бы индикатор начел моргать.
И после этого они заработали. Но на сайте девелопера, так ни чего и не отразилось, но они работают.

Hi!!!
The developer's website does not always correctly display how the device is connected.
Recently I encountered the same problem.
I decided so.
Connect all devices to Homey and then place them in their places, where they need to work through the router.
And then on each device several times pressed the buttons to connect, so that the indicator will blink.
And after that they earned. But on the site of the developer, so that is not reflected, but they work.
