### ISSUE TITLE
Verouderd

### ISSUE THREAD

**Issue by fkooten** [TedTolboom/com.xiaomi-mi-zigbee#74]
Recently I purchased 2 Xiaomi double Wireless switches model WXKG02LM. After installing these switched in Homey I wanted to use them in a flow to control some lights. As soon as I selected the switch in a flow it was considered "Verouderd". I could select the buttons but not the number of times pressed. I removed the switches from Homey and removed the battery to see if I could reset them. This was without any success. Has anyone suggestions to solve this. Thanks in advance for your support

**Comment by TedTolboom** [comment]
@fkooten the triggercards marked as "Verouderd" or "Deprecated" are indeed only partially working and will be removed in the next app update, as mentioned in the changelog:

> Note:
> The old (marked DEPRECATED) flow cards of the wireless switches will be removed in a next release; please rebuild your flows based on the new cards

Please use instead of the old trigger card:
![image](https://user-images.githubusercontent.com/17163431/42098308-d87d0c96-7bba-11e8-905e-5316b0ac0321.png)

the new trigger card:
![image](https://user-images.githubusercontent.com/17163431/42098408-1f6ba8d8-7bbb-11e8-8d29-154a3733af1d.png)

These should work ok...

**Comment by fkooten** [comment]
Thx it does the job
